<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamicData" Version="9.4.33" />
    <PackageReference Include="ReactiveUI.Avalonia.Reactive" Version="12.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Localization.Interfaces\Localization.Interfaces.csproj" />
    <ProjectReference Include="..\MessageBox.Core\MessageBox.Core.csproj" />
    <ProjectReference Include="..\MessageBusTypes\MessageBusTypes.csproj" />
    <ProjectReference Include="..\Services.Interfaces\Services.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Localization.Interfaces" />
  </ItemGroup>

</Project>
